import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

import Authentication from './templates/authentication';
import { useState, useEffect } from 'react';
import { Site, Guest } from './components/inteface';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [site, setSite] = useState<Site | null>(null);

  interface FetchSite {
    method: string;
  }

  const fetchSite = async ({ method }: FetchSite) => {
    try {
      const response = await fetch('../api/site', { method });
      if (response.ok) {
        const data = await response.json();
        setSite(data.site);
      } else {
        throw new Error('Error fetching data');
      }
    } catch (error) {
      console.error(`There was an error: ${error}`);
    }
  };

  const handleSignOut = () => fetchSite({ method: 'POST' });

  useEffect(() => {
    fetchSite({ method: 'GET' });
  }, [site?.signed_in]);

  const guest = site ? site.signed_in.guest as Guest : null;

  return (
    <>
      <Head>
        <title>Captive Portal Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {site ? (
          !site.signed_in.status ? (
            <Authentication />
          ) : (
            <>
              <h2>Welcome {guest?.first_name}! You are signed in!</h2>
              <button onClick={handleSignOut}>Sign Out</button>
            </>
          )
        ) : (
          <h2>Loading</h2>
        )}
      </main>
    </>
  );
}
