import Head from 'next/head';

import { useEffect } from 'react';
import { useRouter } from 'next/router';

import Layout from '../components/layout';

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    router.push('/templates/authentication');
  }, []);

  return (
    <>
      <Head>
        <title>Captive Portal Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout isLoading={true} />
      </main>
    </>
  );
}
